# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/system_bd/system_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd || ORIG_REF_NAME==system_bd} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_processing_system7_0_0/system_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_processing_system7_0_0 || ORIG_REF_NAME==system_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_xlconstant_0_0/system_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_xlconstant_0_0 || ORIG_REF_NAME==system_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_xlslice_0_0/system_bd_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_xlslice_0_0 || ORIG_REF_NAME==system_bd_xlslice_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_axi_uartlite_0_0/system_bd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_axi_uartlite_0_0 || ORIG_REF_NAME==system_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_xbar_0/system_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_xbar_0 || ORIG_REF_NAME==system_bd_xbar_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_ps7_0_axi_periph_0/system_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_rst_ps7_0_50M_0/system_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_0_0/system_bd_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_0_0 || ORIG_REF_NAME==system_bd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_1_0/system_bd_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_1_0 || ORIG_REF_NAME==system_bd_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_2_0/system_bd_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_2_0 || ORIG_REF_NAME==system_bd_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_3_0/system_bd_util_vector_logic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_3_0 || ORIG_REF_NAME==system_bd_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_3_1/system_bd_util_vector_logic_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_3_1 || ORIG_REF_NAME==system_bd_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_3_2/system_bd_util_vector_logic_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_3_2 || ORIG_REF_NAME==system_bd_util_vector_logic_3_2} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_3_3/system_bd_util_vector_logic_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_3_3 || ORIG_REF_NAME==system_bd_util_vector_logic_3_3} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_3_4/system_bd_util_vector_logic_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_3_4 || ORIG_REF_NAME==system_bd_util_vector_logic_3_4} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_3_5/system_bd_util_vector_logic_3_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_3_5 || ORIG_REF_NAME==system_bd_util_vector_logic_3_5} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_1_1/system_bd_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_1_1 || ORIG_REF_NAME==system_bd_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_0_1/system_bd_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_0_1 || ORIG_REF_NAME==system_bd_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_util_vector_logic_10_0/system_bd_util_vector_logic_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_util_vector_logic_10_0 || ORIG_REF_NAME==system_bd_util_vector_logic_10_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_sequencerip_0_0/system_bd_sequencerip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_sequencerip_0_0 || ORIG_REF_NAME==system_bd_sequencerip_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_ad_iobuf_0_0/system_bd_ad_iobuf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_ad_iobuf_0_0 || ORIG_REF_NAME==system_bd_ad_iobuf_0_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_ad_iobuf_1_0/system_bd_ad_iobuf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_ad_iobuf_1_0 || ORIG_REF_NAME==system_bd_ad_iobuf_1_0} -quiet] -quiet

# IP: bd/system_bd/ip/system_bd_auto_pc_0/system_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bd_auto_pc_0 || ORIG_REF_NAME==system_bd_auto_pc_0} -quiet] -quiet

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_processing_system7_0_0/system_bd_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_processing_system7_0_0 || ORIG_REF_NAME==system_bd_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_axi_uartlite_0_0/system_bd_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_axi_uartlite_0_0 || ORIG_REF_NAME==system_bd_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_axi_uartlite_0_0/system_bd_axi_uartlite_0_0_ooc.xdc

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_axi_uartlite_0_0/system_bd_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_axi_uartlite_0_0 || ORIG_REF_NAME==system_bd_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_rst_ps7_0_50M_0/system_bd_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_bd_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_rst_ps7_0_50M_0/system_bd_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_bd_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/ip/system_bd_auto_pc_0/system_bd_auto_pc_0_ooc.xdc

# XDC: f:/Xilinx/projects/s9base/s9base.gen/sources_1/bd/system_bd/system_bd_ooc.xdc
