
############################################################################
# Switch's                                                                                                                                      #
############################################################################

#  S1 /"reset" / MIO[47]
set_property iostandard "LVCMOS25" [get_ports "FIXED_IO_mio[47]"]
set_property PACKAGE_PIN "B14" [get_ports "FIXED_IO_mio[47]"]
set_property PIO_DIRECTION "INPUT" [get_ports "FIXED_IO_mio[47]"]
#  S2 / "ip reset"  / MIO[51]
set_property iostandard "LVCMOS25" [get_ports "FIXED_IO_mio[51]"]
set_property PACKAGE_PIN "B9" [get_ports "FIXED_IO_mio[51]"]
set_property PIO_DIRECTION "INPUT" [get_ports "FIXED_IO_mio[51]"]

############################################################################
# LED's                                                                                                                                         #
############################################################################

#  LED_0 / "red led"  / MIO[37]
set_property iostandard "LVCMOS25" [get_ports "FIXED_IO_mio[37]"]
set_property PACKAGE_PIN "A10" [get_ports "FIXED_IO_mio[37]"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "FIXED_IO_mio[37]"]
#  LED_1 / "green led"  / MIO[38]
set_property iostandard "LVCMOS25" [get_ports "FIXED_IO_mio[38]"]
set_property PACKAGE_PIN "E13" [get_ports "FIXED_IO_mio[38]"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "FIXED_IO_mio[38]"]

#  D1 "DONE_0"/ green //center led, smt #
#  PACKAGE_PIN "R11"                    #

#  D2 / green //center led, smt   / MIO[15]
set_property iostandard "LVCMOS33" [get_ports "FIXED_IO_mio[15]"]
set_property PACKAGE_PIN "C8" [get_ports "FIXED_IO_mio[15]"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "FIXED_IO_mio[15]"]

# lcd pins
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33  } [get_ports { SPI0_MOSI_O_0 }]; #mosi
set_property PIO_DIRECTION OUTPUT [get_ports { SPI0_MOSI_O_0 }];
set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33  } [get_ports { SPI0_SCLK_O_0 }]; #sclk
set_property PIO_DIRECTION OUTPUT [get_ports { SPI0_SCLK_O_0 }];
set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33  } [get_ports { SPI0_SS_O_0 }]; #cs
set_property PIO_DIRECTION OUTPUT [get_ports { SPI0_SS_O_0 }];
set_property -dict { PACKAGE_PIN V20   IOSTANDARD LVCMOS33  } [get_ports { Dout_0[0] }]; #rst - 65
set_property PIO_DIRECTION OUTPUT [get_ports { Dout_0[0] }];
set_property -dict { PACKAGE_PIN W20   IOSTANDARD LVCMOS33  } [get_ports { Dout_0[1] }]; #dc - 66
set_property PIO_DIRECTION OUTPUT [get_ports { Dout_0[1] }];

# uartlite pins
set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33  } [get_ports { ulite_tx_O_0 }]; #tx
set_property PIO_DIRECTION OUTPUT [get_ports { ulite_tx_O_0 }];
set_property -dict { PACKAGE_PIN U20   IOSTANDARD LVCMOS33  } [get_ports { ulite_rx_I_0 }]; #rx
set_property PIO_DIRECTION INPUT [get_ports { ulite_rx_I_0 }];

# seq pins
set_property -dict { PACKAGE_PIN Y18   IOSTANDARD LVCMOS33  } [get_ports { lna144_O }]; 
set_property PIO_DIRECTION OUTPUT [get_ports { lna144_O }];
set_property -dict { PACKAGE_PIN Y19   IOSTANDARD LVCMOS33  } [get_ports { pa144_O }]; 
set_property PIO_DIRECTION OUTPUT [get_ports { pa144_O }];
set_property -dict { PACKAGE_PIN T17   IOSTANDARD LVCMOS33  } [get_ports { a144_O }]; 
set_property PIO_DIRECTION OUTPUT [get_ports { a144_O }];
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33  } [get_ports { lna430_O }]; 
set_property PIO_DIRECTION OUTPUT [get_ports { lna430_O }];
set_property -dict { PACKAGE_PIN R16   IOSTANDARD LVCMOS33  } [get_ports { pa430_O }]; 
set_property PIO_DIRECTION OUTPUT [get_ports { pa430_O }];
set_property -dict { PACKAGE_PIN R17   IOSTANDARD LVCMOS33  } [get_ports { a430_O }]; 
set_property PIO_DIRECTION OUTPUT [get_ports { a430_O }];

set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33  } [get_ports { PTT1_I }]; 
set_property PIO_DIRECTION INPUT [get_ports { PTT1_I }];
set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33  } [get_ports { PTT2_I }]; 
set_property PIO_DIRECTION INPUT [get_ports { PTT2_I }];
set_property -dict { PACKAGE_PIN T20   IOSTANDARD LVCMOS33  } [get_ports { FAULT_I }]; 
set_property PIO_DIRECTION INPUT [get_ports { FAULT_I }];

#  D6 / green //bar led 1 of 4, smt  / 34_L8P
#set_property iostandard "LVCMOS25" [get_ports "IO_L8P_T1_34"]
#set_property PACKAGE_PIN "W14" [get_ports "IO_L8P_T1_34"]
#set_property PIO_DIRECTION "OUTPUT" [get_ports "IO_L8P_T1_34"]
#  D5  / green //bar led  2 of 4, smt  / 34_L7P
#set_property iostandard "LVCMOS25" [get_ports "IO_L7P_T1_34"]
#set_property PACKAGE_PIN "Y16" [get_ports "IO_L7P_T1_34"]
#set_property PIO_DIRECTION "OUTPUT" [get_ports "IO_L7P_T1_34"]
# D8  /  green //bar led 3 of 4, smt  / 34_L9P
#set_property iostandard "LVCMOS25" [get_ports "IO_L9P_T1_DQS_34"]
#set_property PACKAGE_PIN "T16" [get_ports "IO_L9P_T1_DQS_34"]
#set_property PIO_DIRECTION "OUTPUT" [get_ports "IO_L9P_T1_DQS_34"]
# D7  / green //bar led 4 of 4, smt  / 34_L6P
#set_property iostandard "LVCMOS25" [get_ports "IO_L6P_T1_34"]
#set_property PACKAGE_PIN "P14" [get_ports "IO_L6P_T1_34"]
#set_property PIO_DIRECTION "OUTPUT" [get_ports "IO_L6P_T1_34"]

#  D6 / green //bar led 1 of 4, smt
set_property iostandard "LVCMOS33" [get_ports "LED_D6"]
set_property PACKAGE_PIN "M17" [get_ports "LED_D6"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "LED_D6"]
#  D5  / green //bar led  2 of 4, smt  
set_property iostandard "LVCMOS33" [get_ports "LED_D5"]
set_property PACKAGE_PIN "M19" [get_ports "LED_D5"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "LED_D5"]
# D8  /  green //bar led 3 of 4, smt  
set_property iostandard "LVCMOS33" [get_ports "LED_D8"]
set_property PACKAGE_PIN "L19" [get_ports "LED_D8"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "LED_D8"]
# D7  / green //bar led 4 of 4, smt  
set_property iostandard "LVCMOS33" [get_ports "LED_D7"]
set_property PACKAGE_PIN "F16" [get_ports "LED_D7"]
set_property PIO_DIRECTION "OUTPUT" [get_ports "LED_D7"]

# I2C0
set_property iostandard "LVCMOS33" [get_ports "I2C0_SDA"]
set_property iostandard "LVCMOS33" [get_ports "I2C0_SCL"]
set_property PULLUP true [get_ports "I2C0_SDA"]
set_property PULLUP true [get_ports "I2C0_SCL"]
set_property PACKAGE_PIN "W19" [get_ports "I2C0_SDA"]
set_property PACKAGE_PIN "W18" [get_ports "I2C0_SCL"]

############################################################################
# I/O STANDARDS and Location Constraints                                   #
############################################################################

#  Enet 0 / mdio / MIO[53]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[53]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[53]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[53]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[53]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[53]}]
#  Enet 0 / mdc / MIO[52]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[52]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[52]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[52]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[52]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[52]}]
#  UART 1 / rx / MIO[49]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[49]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[49]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[49]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[49]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[49]}]
#  UART 1 / tx / MIO[48]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[48]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[48]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[48]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[48]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[48]}]
#  SD 0 / cd / MIO[46]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[46]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[46]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[46]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[46]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[46]}]
#  SD 0 / data[3] / MIO[45]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[45]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[45]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[45]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[45]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[45]}]
#  SD 0 / data[2] / MIO[44]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[44]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[44]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[44]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[44]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[44]}]
#  SD 0 / data[1] / MIO[43]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[43]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[43]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[43]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[43]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[43]}]
#  SD 0 / data[0] / MIO[42]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[42]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[42]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[42]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[42]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[42]}]
#  SD 0 / cmd / MIO[41]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[41]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[41]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[41]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[41]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[41]}]
#  SD 0 / clk / MIO[40]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[40]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[40]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[40]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[40]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[40]}]
#  Enet 0 / rx_ctl / MIO[27]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[27]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[27]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[27]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[27]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[27]}]
#  Enet 0 / rxd[3] / MIO[26]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[26]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[26]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[26]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[26]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[26]}]
#  Enet 0 / rxd[2] / MIO[25]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[25]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[25]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[25]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[25]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[25]}]
#  Enet 0 / rxd[1] / MIO[24]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[24]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[24]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[24]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[24]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[24]}]
#  Enet 0 / rxd[0] / MIO[23]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[23]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[23]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[23]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[23]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[23]}]
#  Enet 0 / rx_clk / MIO[22]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[22]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[22]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[22]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[22]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[22]}]
#  Enet 0 / tx_ctl / MIO[21]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[21]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[21]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[21]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[21]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[21]}]
#  Enet 0 / txd[3] / MIO[20]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[20]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[20]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[20]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[20]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[20]}]
#  Enet 0 / txd[2] / MIO[19]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[19]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[19]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[19]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[19]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[19]}]
#  Enet 0 / txd[1] / MIO[18]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[18]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[18]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[18]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[18]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[18]}]
#  Enet 0 / txd[0] / MIO[17]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[17]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[17]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[17]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[17]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[17]}]
#  Enet 0 / tx_clk / MIO[16]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[16]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[16]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[16]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[16]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[16]}]


#  NAND Flash / busy / MIO[14]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[14]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[14]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[14]}]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[14]}]
#  NAND Flash / data[3] / MIO[13]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[13]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[13]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[13]}]
#  NAND Flash / data[7] / MIO[12]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[12]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[12]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[12]}]
#  NAND Flash / data[6] / MIO[11]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[11]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[11]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[11]}]
#  NAND Flash / data[5] / MIO[10]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[10]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[10]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[10]}]
#  NAND Flash / data[4] / MIO[9]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[9]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[9]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[9]}]
#  NAND Flash / re_b / MIO[8]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[8]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[8]}]
#  NAND Flash / cle / MIO[7]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[7]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[7]}]
#  NAND Flash / data[1] / MIO[6]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[6]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[6]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[6]}]
#  NAND Flash / data[0] / MIO[5]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[5]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[5]}]
#  NAND Flash / data[2] / MIO[4]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[4]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[4]}]
#  NAND Flash / we_b / MIO[3]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[3]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[3]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[3]}]
#  NAND Flash / ale / MIO[2]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[2]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[2]}]
#  NAND Flash / cs / MIO[0]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[0]}]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[0]}]
set_property PULLUP true [get_ports {FIXED_IO_mio[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[0]}]


# DDR
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrp]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrp]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrp]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrn]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrn]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrn]
set_property IOSTANDARD SSTL15 [get_ports DDR_we_n]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_we_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_ras_n]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ras_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_odt]
set_property SLEW SLOW [get_ports DDR_odt]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_odt]
set_property IOSTANDARD SSTL15 [get_ports DDR_reset_n]
set_property SLEW FAST [get_ports DDR_reset_n]
set_property PIO_DIRECTION BIDIR [get_ports DDR_reset_n]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[3]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[2]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_p[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[3]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[2]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[1]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[0]}]
set_property SLEW FAST [get_ports {DDR_dqs_n[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[9]}]
set_property SLEW FAST [get_ports {DDR_dq[9]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[9]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[8]}]
set_property SLEW FAST [get_ports {DDR_dq[8]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[8]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[7]}]
set_property SLEW FAST [get_ports {DDR_dq[7]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[7]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[6]}]
set_property SLEW FAST [get_ports {DDR_dq[6]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[6]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[5]}]
set_property SLEW FAST [get_ports {DDR_dq[5]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[5]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[4]}]
set_property SLEW FAST [get_ports {DDR_dq[4]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[4]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[3]}]
set_property SLEW FAST [get_ports {DDR_dq[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[31]}]
set_property SLEW FAST [get_ports {DDR_dq[31]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[31]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[30]}]
set_property SLEW FAST [get_ports {DDR_dq[30]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[30]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[2]}]
set_property SLEW FAST [get_ports {DDR_dq[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[29]}]
set_property SLEW FAST [get_ports {DDR_dq[29]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[29]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[28]}]
set_property SLEW FAST [get_ports {DDR_dq[28]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[28]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[27]}]
set_property SLEW FAST [get_ports {DDR_dq[27]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[27]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[26]}]
set_property SLEW FAST [get_ports {DDR_dq[26]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[26]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[25]}]
set_property SLEW FAST [get_ports {DDR_dq[25]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[25]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[24]}]
set_property SLEW FAST [get_ports {DDR_dq[24]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[24]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[23]}]
set_property SLEW FAST [get_ports {DDR_dq[23]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[23]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[22]}]
set_property SLEW FAST [get_ports {DDR_dq[22]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[22]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[21]}]
set_property SLEW FAST [get_ports {DDR_dq[21]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[21]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[20]}]
set_property SLEW FAST [get_ports {DDR_dq[20]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[20]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[1]}]
set_property SLEW FAST [get_ports {DDR_dq[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[19]}]
set_property SLEW FAST [get_ports {DDR_dq[19]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[19]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[18]}]
set_property SLEW FAST [get_ports {DDR_dq[18]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[18]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[17]}]
set_property SLEW FAST [get_ports {DDR_dq[17]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[17]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[16]}]
set_property SLEW FAST [get_ports {DDR_dq[16]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[16]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[15]}]
set_property SLEW FAST [get_ports {DDR_dq[15]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[15]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[14]}]
set_property SLEW FAST [get_ports {DDR_dq[14]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[14]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[13]}]
set_property SLEW FAST [get_ports {DDR_dq[13]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[13]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[12]}]
set_property SLEW FAST [get_ports {DDR_dq[12]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[12]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[11]}]
set_property SLEW FAST [get_ports {DDR_dq[11]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[11]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[10]}]
set_property SLEW FAST [get_ports {DDR_dq[10]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[10]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[0]}]
set_property SLEW FAST [get_ports {DDR_dq[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[0]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[3]}]
set_property SLEW FAST [get_ports {DDR_dm[3]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[3]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[2]}]
set_property SLEW FAST [get_ports {DDR_dm[2]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[2]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[1]}]
set_property SLEW FAST [get_ports {DDR_dm[1]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[1]}]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[0]}]
set_property SLEW FAST [get_ports {DDR_dm[0]}]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports DDR_cs_n]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cs_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_cke]
set_property SLEW SLOW [get_ports DDR_cke]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cke]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_p]
set_property SLEW FAST [get_ports DDR_ck_p]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_n]
set_property SLEW FAST [get_ports DDR_ck_n]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_n]
set_property IOSTANDARD SSTL15 [get_ports DDR_cas_n]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cas_n]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[2]}]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[1]}]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[0]}]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[9]}]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[8]}]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[7]}]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[6]}]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[5]}]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[4]}]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[3]}]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[2]}]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[1]}]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[14]}]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[13]}]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[12]}]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[11]}]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[10]}]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[0]}]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property SLEW FAST [get_ports FIXED_IO_ps_porb]
set_property IOSTANDARD LVCMOS25 [get_ports FIXED_IO_ps_srstb]
set_property SLEW FAST [get_ports FIXED_IO_ps_srstb]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN B10 [get_ports FIXED_IO_ps_srstb]
set_property PACKAGE_PIN P4 [get_ports DDR_ras_n]
set_property PACKAGE_PIN C7 [get_ports FIXED_IO_ps_porb]
set_property PACKAGE_PIN N5 [get_ports DDR_odt]
set_property PACKAGE_PIN C11 [get_ports {FIXED_IO_mio[53]}]
set_property PACKAGE_PIN C10 [get_ports {FIXED_IO_mio[52]}]
set_property PACKAGE_PIN C12 [get_ports {FIXED_IO_mio[49]}]
set_property PACKAGE_PIN B12 [get_ports {FIXED_IO_mio[48]}]
set_property PACKAGE_PIN D16 [get_ports {FIXED_IO_mio[46]}]
set_property PACKAGE_PIN B15 [get_ports {FIXED_IO_mio[45]}]
set_property PACKAGE_PIN F13 [get_ports {FIXED_IO_mio[44]}]
set_property PACKAGE_PIN A9 [get_ports {FIXED_IO_mio[43]}]
set_property PACKAGE_PIN E12 [get_ports {FIXED_IO_mio[42]}]
set_property PACKAGE_PIN C17 [get_ports {FIXED_IO_mio[41]}]
set_property PACKAGE_PIN D14 [get_ports {FIXED_IO_mio[40]}]
set_property PACKAGE_PIN D13 [get_ports {FIXED_IO_mio[27]}]
set_property PACKAGE_PIN A15 [get_ports {FIXED_IO_mio[26]}]
set_property PACKAGE_PIN F15 [get_ports {FIXED_IO_mio[25]}]
set_property PACKAGE_PIN A16 [get_ports {FIXED_IO_mio[24]}]
set_property PACKAGE_PIN D11 [get_ports {FIXED_IO_mio[23]}]
set_property PACKAGE_PIN B17 [get_ports {FIXED_IO_mio[22]}]
set_property PACKAGE_PIN F14 [get_ports {FIXED_IO_mio[21]}]
set_property PACKAGE_PIN A17 [get_ports {FIXED_IO_mio[20]}]
set_property PACKAGE_PIN D10 [get_ports {FIXED_IO_mio[19]}]
set_property PACKAGE_PIN B18 [get_ports {FIXED_IO_mio[18]}]
set_property PACKAGE_PIN E14 [get_ports {FIXED_IO_mio[17]}]
set_property PACKAGE_PIN A19 [get_ports {FIXED_IO_mio[16]}]
set_property PACKAGE_PIN C5 [get_ports {FIXED_IO_mio[14]}]
set_property PACKAGE_PIN E8 [get_ports {FIXED_IO_mio[13]}]
set_property PACKAGE_PIN D9 [get_ports {FIXED_IO_mio[12]}]
set_property PACKAGE_PIN C6 [get_ports {FIXED_IO_mio[11]}]
set_property PACKAGE_PIN E9 [get_ports {FIXED_IO_mio[10]}]
set_property PACKAGE_PIN B5 [get_ports {FIXED_IO_mio[9]}]
set_property PACKAGE_PIN D5 [get_ports {FIXED_IO_mio[8]}]
set_property PACKAGE_PIN D8 [get_ports {FIXED_IO_mio[7]}]
set_property PACKAGE_PIN A5 [get_ports {FIXED_IO_mio[6]}]
set_property PACKAGE_PIN A6 [get_ports {FIXED_IO_mio[5]}]
set_property PACKAGE_PIN B7 [get_ports {FIXED_IO_mio[4]}]
set_property PACKAGE_PIN D6 [get_ports {FIXED_IO_mio[3]}]
set_property PACKAGE_PIN B8 [get_ports {FIXED_IO_mio[2]}]
set_property PACKAGE_PIN E6 [get_ports {FIXED_IO_mio[0]}]
set_property PACKAGE_PIN B4 [get_ports DDR_reset_n]
set_property PACKAGE_PIN W5 [get_ports {DDR_dqs_p[3]}]
set_property PACKAGE_PIN M5 [get_ports DDR_we_n]
set_property PACKAGE_PIN G5 [get_ports FIXED_IO_ddr_vrn]
set_property PACKAGE_PIN H5 [get_ports FIXED_IO_ddr_vrp]
set_property PACKAGE_PIN N2 [get_ports {DDR_addr[0]}]
set_property PACKAGE_PIN K2 [get_ports {DDR_addr[1]}]
set_property PACKAGE_PIN M3 [get_ports {DDR_addr[2]}]
set_property PACKAGE_PIN K3 [get_ports {DDR_addr[3]}]
set_property PACKAGE_PIN M4 [get_ports {DDR_addr[4]}]
set_property PACKAGE_PIN L1 [get_ports {DDR_addr[5]}]
set_property PACKAGE_PIN L4 [get_ports {DDR_addr[6]}]
set_property PACKAGE_PIN K4 [get_ports {DDR_addr[7]}]
set_property PACKAGE_PIN K1 [get_ports {DDR_addr[8]}]
set_property PACKAGE_PIN J4 [get_ports {DDR_addr[9]}]
set_property PACKAGE_PIN F5 [get_ports {DDR_addr[10]}]
set_property PACKAGE_PIN G4 [get_ports {DDR_addr[11]}]
set_property PACKAGE_PIN E4 [get_ports {DDR_addr[12]}]
set_property PACKAGE_PIN F4 [get_ports {DDR_addr[14]}]
set_property PACKAGE_PIN D4 [get_ports {DDR_addr[13]}]
set_property PACKAGE_PIN L5 [get_ports {DDR_ba[0]}]
set_property PACKAGE_PIN R4 [get_ports {DDR_ba[1]}]
set_property PACKAGE_PIN J5 [get_ports {DDR_ba[2]}]
set_property PACKAGE_PIN P5 [get_ports DDR_cas_n]
set_property PACKAGE_PIN N3 [get_ports DDR_cke]
set_property PACKAGE_PIN M2 [get_ports DDR_ck_n]
set_property PACKAGE_PIN L2 [get_ports DDR_ck_p]
set_property PACKAGE_PIN E7 [get_ports FIXED_IO_ps_clk]
set_property PACKAGE_PIN N1 [get_ports DDR_cs_n]
set_property PACKAGE_PIN A1 [get_ports {DDR_dm[0]}]
set_property PACKAGE_PIN F1 [get_ports {DDR_dm[1]}]
set_property PACKAGE_PIN T1 [get_ports {DDR_dm[2]}]
set_property PACKAGE_PIN Y1 [get_ports {DDR_dm[3]}]
set_property PACKAGE_PIN C3 [get_ports {DDR_dq[0]}]
set_property PACKAGE_PIN B3 [get_ports {DDR_dq[1]}]
set_property PACKAGE_PIN A2 [get_ports {DDR_dq[2]}]
set_property PACKAGE_PIN A4 [get_ports {DDR_dq[3]}]
set_property PACKAGE_PIN D3 [get_ports {DDR_dq[4]}]
set_property PACKAGE_PIN D1 [get_ports {DDR_dq[5]}]
set_property PACKAGE_PIN C1 [get_ports {DDR_dq[6]}]
set_property PACKAGE_PIN E1 [get_ports {DDR_dq[7]}]
set_property PACKAGE_PIN E2 [get_ports {DDR_dq[8]}]
set_property PACKAGE_PIN E3 [get_ports {DDR_dq[9]}]
set_property PACKAGE_PIN G3 [get_ports {DDR_dq[10]}]
set_property PACKAGE_PIN H3 [get_ports {DDR_dq[11]}]
set_property PACKAGE_PIN J3 [get_ports {DDR_dq[12]}]
set_property PACKAGE_PIN H2 [get_ports {DDR_dq[13]}]
set_property PACKAGE_PIN H1 [get_ports {DDR_dq[14]}]
set_property PACKAGE_PIN J1 [get_ports {DDR_dq[15]}]
set_property PACKAGE_PIN P1 [get_ports {DDR_dq[16]}]
set_property PACKAGE_PIN P3 [get_ports {DDR_dq[17]}]
set_property PACKAGE_PIN R3 [get_ports {DDR_dq[18]}]
set_property PACKAGE_PIN R1 [get_ports {DDR_dq[19]}]
set_property PACKAGE_PIN T4 [get_ports {DDR_dq[20]}]
set_property PACKAGE_PIN U4 [get_ports {DDR_dq[21]}]
set_property PACKAGE_PIN U2 [get_ports {DDR_dq[22]}]
set_property PACKAGE_PIN U3 [get_ports {DDR_dq[23]}]
set_property PACKAGE_PIN V1 [get_ports {DDR_dq[24]}]
set_property PACKAGE_PIN Y3 [get_ports {DDR_dq[25]}]
set_property PACKAGE_PIN W1 [get_ports {DDR_dq[26]}]
set_property PACKAGE_PIN Y4 [get_ports {DDR_dq[27]}]
set_property PACKAGE_PIN Y2 [get_ports {DDR_dq[28]}]
set_property PACKAGE_PIN W3 [get_ports {DDR_dq[29]}]
set_property PACKAGE_PIN V2 [get_ports {DDR_dq[30]}]
set_property PACKAGE_PIN V3 [get_ports {DDR_dq[31]}]
set_property PACKAGE_PIN B2 [get_ports {DDR_dqs_n[0]}]
set_property PACKAGE_PIN F2 [get_ports {DDR_dqs_n[1]}]
set_property PACKAGE_PIN T2 [get_ports {DDR_dqs_n[2]}]
set_property PACKAGE_PIN W4 [get_ports {DDR_dqs_n[3]}]
set_property PACKAGE_PIN C2 [get_ports {DDR_dqs_p[0]}]
set_property PACKAGE_PIN G2 [get_ports {DDR_dqs_p[1]}]
set_property PACKAGE_PIN R2 [get_ports {DDR_dqs_p[2]}]
set_property SLEW FAST [get_ports FIXED_IO_ps_clk]
